/* CSCI 200: Assignment 2: A2 - Watch the Wumpus
 *
 * Author: Dr. Jeffrey Paone
 *
 * Starting template to process a Wumpus Game History (.wgh) file and
 * output the corresponding game log.
 *
 * DO NOT EDIT THIS FILE
 */

#include "wumpus_functions.h"

#include <fstream>
#include <iostream>
#include <string>
using namespace std;

int main() {
    const string WUMPUS_FILE_NAME = enter_wumpus_file();
    const string GAME_LOG_FILE_NAME = enter_game_log_file();

    ifstream wumpusFileIn;
    ofstream gameLogOut;
    
    if( !open_files(wumpusFileIn, gameLogOut, WUMPUS_FILE_NAME, GAME_LOG_FILE_NAME) ) {
        cerr << "Error opening files" << endl;
        return -1;
    }

    int caveWidth, caveHeight; 
    read_world_header(wumpusFileIn, caveWidth, caveHeight);

    int wumpusX = -1, wumpusY = -1;
    int heroX = -1, heroY = -1;
    int pitX = -1, pitY = -1;

    if( !read_object_header(wumpusFileIn,
                            wumpusX, wumpusY,
                            heroX, heroY,
                            pitX, pitY) ) {
        cerr << "Not all objects placed in world" << endl;
        return -2;
    }
    
    cout << endl;

    int numMoves;
    read_number_moves(wumpusFileIn, numMoves);
    
    const bool PLAY_AS_HERO = choose_player();

    play_game(wumpusFileIn, gameLogOut,
              caveWidth, caveHeight,
              numMoves,
              wumpusX, wumpusY,
              heroX, heroY,
              pitX, pitY,
              PLAY_AS_HERO);

    return 0;
}