/* CSCI 200: Final Project
 *
 * Author: Isaac March
 * Resources used (Office Hours, Tutoring, Other Students, etc & in what capacity):
 *     // StackOverflow
 *     // Cplusplus.com
 *     // www.youtube.com/watch?v=vkS1fY_UTyg&t=49s&ab_channel=Kofybrek this  // these youTube chanels were helpful for finding out how much can be done with SFML
 *     // www.youtube.com/watch?v=kxb0GvBNOGU&ab_channel=SurajSharma
 *     // www.sfml-dev.org/documentation/2.6.0/  // SFML developer documentation
 *
 * Main.cpp sets up the board and runs the game while recording the score for each player.
 */

#include "Player.hpp"
#include "global.hpp"
#include "Enemy.hpp"
#include "gameFunctions.hpp"

#include <string>
#include <iostream>
#include <cmath>
#include <vector>

using namespace std;

// main should run the start window
int main() {
    // seed random value

    // define variabels that will be used throughout the game
    string username, topPlayer;
    int highScore = 0, score;
    char keyIn;
    bool start = true;
    vector<string> users;
    vector<int> scores;

    // open and validate files
    string saveFile = "data/scores.txt";

    while (start) { // game will repeat endlessly looping from game menu untill the user decides to quit
        getScores(saveFile, users, scores); // retrive all save data and wrtie to a vector that can be read by function findTopPlayer
        findTopPlayer(highScore, topPlayer, users, scores); // find top scoring players based on the vectors generated by getScores function
        displayTitle(topPlayer, highScore); // display introduction with high scoring player with their username
        cin >> keyIn;
        if (keyIn == 'Q' || keyIn == 'q') { // if user hits q or Q game exits
            cout << "Thanks for playing!" << endl;
            start = false;
            return 0;
        } else if (keyIn == 'S' || keyIn == 's') { // if user hits s or S game will start
            clear_screen();
            start = true;
            // Play game
            playGame(score);

            // write new scores to score file
            cout << "Enter your username: ";
            cin >> username; cout << endl;
            //username = "LazerBrain"; // Change this to the desired username delete when done debugging
            writeScores(saveFile, username, score);
        }
    }

    return 0;
}